"""empty message

Revision ID: 51e3d2808a1b
Revises: e773f9b8d47e
Create Date: 2016-05-25 10:13:26.232150

"""

# revision identifiers, used by Alembic.
revision = '51e3d2808a1b'
down_revision = 'e773f9b8d47e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('recaptcha_end_datetime', sa.DateTime(), nullable=True))
    op.add_column('config', sa.Column('recaptcha_start_datetime', sa.DateTime(), nullable=True))
    op.add_column('config', sa.Column('show_recaptcha', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'show_recaptcha')
    op.drop_column('config', 'recaptcha_start_datetime')
    op.drop_column('config', 'recaptcha_end_datetime')
    ### end Alembic commands ###
