"""empty message

Revision ID: 6fbcaf6adb06
Revises: None
Create Date: 2016-05-23 13:39:06.515555

"""

# revision identifiers, used by Alembic.
revision = '6fbcaf6adb06'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'failed_login_attempts')
    ### end Alembic commands ###
