"""empty message

Revision ID: e773f9b8d47e
Revises: None
Create Date: 2016-05-24 10:54:54.088631

"""

# revision identifiers, used by Alembic.
revision = 'e773f9b8d47e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('config', sa.Column('recaptcha_end_datetime', sa.DateTime(), nullable=True))
    op.add_column('config', sa.Column('recaptcha_start_datetime', sa.DateTime(), nullable=True))
    op.add_column('config', sa.Column('show_recaptcha', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_login_attempt')
    op.drop_column('config', 'show_recaptcha')
    op.drop_column('config', 'recaptcha_start_datetime')
    op.drop_column('config', 'recaptcha_end_datetime')
    ### end Alembic commands ###
